CREATE USER EVALUACION2 IDENTIFIED BY "Mdy2131-Prueba2"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER EVALUACION2 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO EVALUACION2;
GRANT "RESOURCE" TO EVALUACION2;
ALTER USER EVALUACION2 DEFAULT ROLE "RESOURCE";